name: Integration testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#        with:
#          submodules: 'true'
      - name: Integration testing
        run: |
          docker-compose up --exit-code-from jrcplightning --quiet-pull
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          path: /workdir/code/build/reports/tests/test/index.html
          #TODO: upload also the lightning node log